# Default values for vote.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
image:
  repository: dockersamples/examplevotingapp_vote
  tag: before

redis:
  usePassword: false

replicaCount: 1

ingress:
  foo: bar
