apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  ports:
  - name: "frontend-service"
    port: 80
    targetPort: 80
    nodePort: 31000
  selector:
    app: guestbook
