apiVersion: v1
kind: LimitRange
metadata:  
  namespace: foo
  name: bar
spec:
  limits:
  - default:
      memory: 512Mi
      cpu: 1
    defaultRequest:
      memory: 256Mi
      cpu: 0.5
    type: Container
