apiVersion: v1
kind: PersistentVolume
metadata:
  name: ______________ 
spec:
  storageClassName: manual
  capacity:
    storage: "1Gi"
  accessModes:
    - "ReadWriteOnce"
  hostPath:
    path: /data/pv

