apiVersion: v1
description: Helm Chart example-voting-app
name: traefik-helm
keywords:
- kubernetes
- example-voting-app
version: 0.0.1
sources:
- https://github.com/zepouet/jenkins-mastering-k8s
maintainers:
- name: Nicolas Muller
  email: n.muller@treeptik.fr
