apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: teapot-green
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: demobg
        deployment: green
    spec:
      containers:
      - name: teapot
        image: treeptik/nginx:green
        ports:
        - containerPort: 80
        readinessProbe:
           tcpSocket:
              port: 80
           initialDelaySeconds: 2
           periodSeconds: 1

