apiVersion: v1
kind: Service
metadata:
  name: demobg
spec:
  type: NodePort
  selector:
    app: demobg
    deployment: ${COLOR}
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30010
      protocol: TCP

